### PR TITLE
Proposing Sydney logo

### PR DESCRIPTION
**Pull request by vitalbone**
Hi, this is my proposal for the Design Competition @rvagg outlined in https://github.com/nodeschool/sydney/issues/13. Big shout out to @BorisBozic who helped with turning my amateurish sketch into an awesome vector.

Happy for any feedback/discussion/thoughts.

🏙

### CODE REVIEW

**Review by nkbt — APPROVED** [review]
Sick

**Comment by rvagg** [comment]
Beauty mate, I love this.

@nkbt @rprieto @ButenkoT any thoughts on how to move forward with this? Should we put a call out for additional entries for this?

When we accept a final version I'd be happy to try and get NodeSource to pay for a batch of them from StickerMule that can be shared around to everyone running events.

**Comment by ButenkoT** [comment]
@rvagg @nkbt @rprieto  I think the design is quite nice and we should process with it. If we wait for more entries we might end up having same discussion in a year about same things with no stickers.

Print them out! :)

**Comment by rvagg** [comment]
@ButenkoT yeah, I'm of a similar mind actually, this design is fantastic. Anyone else in this repo want to offer an opinion before we roll on with momentum here?

**Comment by rprieto** [comment]
Love your design @vitalbone. I agree with @ButenkoT, let's print!

**Comment by vitalbone** [comment]
Thanks everyone! Let me know if I can be of any help with getting the stickers printed.

**Comment by vitalbone** [comment]
Ok the consensus seems to be that everyone's happy with the design. I hate to be the one that merges my own PR but figured we might as well push this thing along so we can add it to http://nodeschool.io/hexdex

Please feel free to chastise me if I'm being out of line 😅

**Pull request merged**
